FROM golang:1.19-alpine AS build-base

WORKDIR /app

COPY go.mod .

RUN go mod download

COPY . .

RUN go build -o ./out/golang-app .


FROM alpine:3.16.2

COPY --from=build-base /app/out/golang-app  /app/golang-app

CMD  ["/app/golang-app"]